version: '2'
services:
    luckystar-app:
        image: luckystar
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://luckystar-mysql:3306/luckystar?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    luckystar-mysql:
        extends:
            file: mysql.yml
            service: luckystar-mysql
